name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests (native-tls)
        run: cargo test --verbose
      - name: Run tests (rustls)
        run: cargo test --verbose --no-default-features --features=rustls
